In [7]:
#Start of the Program
#Import necessary Program Language
import numpy as np

#Create a random ndarray and store variable X
X = np.random.random((5, 5))

#Computation for the mean and standard deviation of variable X
mean = np.mean(X)
dev = np.std(X)

#Normalize variable X using the formula given "Z = (X - xbar) / std"
Z = (X - mean) / dev

#Print or Display the normalized variables
print(Z)

[[-0.68983198  0.29309526 -0.99112078  1.529191   -1.71335535]
 [-0.48349162 -1.12908911 -0.23523965  0.52228773 -0.69283069]
 [ 0.25070069 -1.04538645 -1.36644976  0.65331351 -0.16762919]
 [-0.29578745 -0.39031816  0.46145794  1.00267272  1.74074197]
 [-1.12268723  1.80960977  1.67029921  0.6939449  -0.30409728]]
